- name: Patch Linux servers
  hosts: all
  become: yes
  tasks:
  - name: Update package cache
    package:
      name: '*'
      state: latest
  - name: Upgrade all packages
    package:
      name: '*'
      state: latest
  - name: Check for any updates after upgrade
    shell: yum check-update
    register: check_update_result
  - name: Install available updates
    shell: yum update -y
    when: check_update_result.stdout != ""